"""
Veritas Reporter — Darknet Audit Report Generator
Converts raw darknet scraper findings into forensic-grade markdown reports.
"""

import json
from datetime import datetime
from typing import Any, Dict, List, Optional
from pathlib import Path

class DarknetReporter:
    """Generates forensic reports for Darknet/Onion service audits."""

    def __init__(self, output_dir: str = "reports/darknet"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate_report(self, target_url: str, audit_data: Dict[str, Any]) -> str:
        """Generate a Markdown report from audit data."""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        safe_name = target_url.replace("http://", "").replace("https://", "").replace(".onion", "").replace("/", "_")
        report_file = self.output_dir / f"audit_{safe_name}_{int(datetime.now().timestamp())}.md"

        report = [
            f"# Veritas Darknet Audit Report",
            f"**Target:** {target_url}",
            f"**Timestamp:** {timestamp}",
            f"**Status:** {'🔴 CRITICAL THREAT' if audit_data.get('threat_level') in ['high', 'critical'] else '🟢 CLEAR'}",
            "\n## 1. Executive Summary",
            f"The darknet audit of target `{target_url}` identified a threat level of **{audit_data.get('threat_level', 'unknown').upper()}** "
            f"with a confidence score of **{audit_data.get('confidence', 0.0):.2f}**.",
            "\n## 2. Infrastructure & Uptime",
            f"- **Onion Address:** `{audit_data.get('url', 'N/A')}`",
            f"- **Status:** {'UP' if audit_data.get('is_up') else 'DOWN'}",
            f"- **Response Time:** {audit_data.get('response_time_ms', 0)}ms",
            f"- **Server Signature:** `{audit_data.get('server', 'Hidden')}`",
            "\n## 3. Threat Classification",
            f"- **Category:** {audit_data.get('classification', 'Uncategorized')}",
            f"- **Detected Patterns:** {', '.join(audit_data.get('detected_patterns', ['None']))}",
            "\n## 4. Forensic Evidence",
            "```json",
            json.dumps(audit_data, indent=2),
            "```",
            "\n---",
            "*Generated by Elliot AI — Phase 12 Darknet Auditor*"
        ]

        content = "\n".join(report)
        report_file.write_text(content)
        return str(report_file)
